trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  pool: Azure
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: DotNetCoreCLI@1
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: src/Web/WebDrapo
        verbose: false
    - task: gulp@0
      displayName: 'gulp buildDrapoLib:tslint'
      inputs:
        gulpFile: src/Web/WebDrapo/gulpfile.js
        targets: 'buildDrapoLib:tslint'
    - task: DotNetCoreCLI@1
      displayName: Build
      inputs:
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
    - task: DotNetCoreCLI@1
      displayName: Test
      inputs:
        command: test
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
      enabled: false
    - task: DotNetCoreCLI@1
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: false
    - task: NuGetCommand@2
      displayName: 'NuGet pack'
      inputs:
        command: pack
        packagesToPack: '**\*.nuspec'
        versioningScheme: byBuildNumber
    - task: NuGetCommand@2
      displayName: 'NuGet push VSTS'
      inputs:
        command: push
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        publishVstsFeed: '716f73eb-2942-4cb4-811d-b2f48cf0c105'
    - task: NuGetCommand@2
      displayName: 'NuGet push nuget'
      inputs:
        command: push
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: external
        publishFeedCredentials: nuget
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()
    - task: DotNetCoreCLI@1
      displayName: 'Publish Docker'
      inputs:
        command: publish
        arguments: '--configuration $(BuildConfiguration) --output published'
        zipAfterPublish: false
    - task: Docker@0
      displayName: 'Remove an Image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryConnection: drapo
        action: 'Run a Docker command'
        customCommand: 'rmi drapo/demo --force'
      continueOnError: true
    - task: Docker@0
      displayName: 'Build an image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryConnection: drapo
        dockerFile: '**/published/**/*Dockerfile'
        imageName: drapo/demo
    - task: Docker@0
      displayName: 'Push an image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryConnection: drapo
        action: 'Push an image'
        imageName: drapo/demo
        includeLatestTag: true